{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "432bcee3-7abe-4e94-a118-985fe49d0b0d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Todos del 1 al 10:\n",
      "  For:\n",
      "1.0\n",
      "2.0\n",
      "3.0\n",
      "4.0\n",
      "5.0\n",
      "6.0\n",
      "7.0\n",
      "8.0\n",
      "9.0\n",
      "10.0\n",
      "  While:\n",
      "1.0\n",
      "2.0\n",
      "3.0\n",
      "4.0\n",
      "5.0\n",
      "6.0\n",
      "7.0\n",
      "8.0\n",
      "9.0\n",
      "10.0\n",
      "Pares:\n",
      "  For:\n",
      "2.0\n",
      "4.0\n",
      "6.0\n",
      "8.0\n",
      "10.0\n",
      "  While:\n",
      "2.0\n",
      "4.0\n",
      "6.0\n",
      "8.0\n",
      "10.0\n",
      "Impares divisibles por 3:\n",
      "  For:\n",
      "3.0\n",
      "6.0\n",
      "9.0\n",
      "  While:\n",
      "3.0\n",
      "6.0\n",
      "9.0\n",
      "Secuencia completada\n"
     ]
    }
   ],
   "source": [
    "#Retos bucles\n",
    "\n",
    "#Reto 1\n",
    "num = [1.00, 2.00, 3.00, 4.00, 5.00, 6.00, 7.00, 8.00, 9.00, 10.00]\n",
    "try:\n",
    "    print(\"Todos del 1 al 10:\")\n",
    "    print(\"  For:\")\n",
    "    for i in range(10):\n",
    "        print(num[i])\n",
    "    print(\"  While:\")\n",
    "    i = 0\n",
    "    while(i<10):\n",
    "        print(num[i])\n",
    "        i = i + 1\n",
    "    print(\"Pares:\")\n",
    "    print(\"  For:\")\n",
    "    for i in range(1, 10, 2):\n",
    "        print(num[i])\n",
    "    print(\"  While:\")\n",
    "    i = 1\n",
    "    while(i<10):\n",
    "        print(num[i])\n",
    "        i = i + 2\n",
    "    print(\"Impares divisibles por 3:\")\n",
    "    print(\"  For:\")\n",
    "    for i in range(1, 10, 1):\n",
    "        if i % 3 == 0: \n",
    "            print(num[i-1])\n",
    "    print(\"  While:\")\n",
    "    i = 1\n",
    "    while(i<10):\n",
    "        i = i + 1\n",
    "        if i % 3 == 0:  \n",
    "            print(num[i-1])\n",
    "except: print(\"Ha habido un problema\")\n",
    "finally: print(\"Secuencia completada\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "587ddeab-1865-4cb9-ab25-af4c2dcdd926",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Elementos de la lista personas\n",
      "  For:\n",
      "{'nombre': 'Luis', 'apellido': 'Perez', 'anyoNacimiento': 1980, 'aficiones': ['bailar', 'escribir'], 'dni': {'anyoExpedicion': 2004, 'lugarNacimento': 'Tenerife'}, 'colorPelo': 'rubio'}\n",
      "{'nombre': 'Carla', 'apellido': 'Perez', 'anyoNacimiento': 2009, 'aficiones': ['badminton', 'caminar'], 'dni': {'anyoExpedicion': 2002, 'lugarNacimento': 'Segovia'}, 'colorPelo': 'negro'}\n",
      "{'nombre': 'Felipe', 'apellido': 'Perez', 'anyoNacimiento': 2003, 'aficiones': ['baloncesto', 'programacion'], 'dni': {'anyoExpedicion': 2011, 'lugarNacimento': 'Zamora'}, 'colorPelo': 'rubio'}\n",
      "{'nombre': 'Monica', 'apellido': 'Perez', 'anyoNacimiento': 1997, 'aficiones': ['baile', 'pintar'], 'dni': {'anyoExpedicion': 2011, 'lugarNacimento': 'Pontevedra'}, 'colorPelo': 'castaño'}\n",
      "  While:\n",
      "{'nombre': 'Luis', 'apellido': 'Perez', 'anyoNacimiento': 1980, 'aficiones': ['bailar', 'escribir'], 'dni': {'anyoExpedicion': 2004, 'lugarNacimento': 'Tenerife'}, 'colorPelo': 'rubio'}\n",
      "{'nombre': 'Carla', 'apellido': 'Perez', 'anyoNacimiento': 2009, 'aficiones': ['badminton', 'caminar'], 'dni': {'anyoExpedicion': 2002, 'lugarNacimento': 'Segovia'}, 'colorPelo': 'negro'}\n",
      "{'nombre': 'Felipe', 'apellido': 'Perez', 'anyoNacimiento': 2003, 'aficiones': ['baloncesto', 'programacion'], 'dni': {'anyoExpedicion': 2011, 'lugarNacimento': 'Zamora'}, 'colorPelo': 'rubio'}\n",
      "{'nombre': 'Monica', 'apellido': 'Perez', 'anyoNacimiento': 1997, 'aficiones': ['baile', 'pintar'], 'dni': {'anyoExpedicion': 2011, 'lugarNacimento': 'Pontevedra'}, 'colorPelo': 'castaño'}\n",
      "Nacidos entre 1978 y 2000\n",
      "  For:\n",
      "Luis tu edad esta entre 40 y 20 años\n",
      "Carla tu edad es menor de 20 años\n",
      "Felipe tu edad es menor de 20 años\n",
      "Monica tu edad esta entre 40 y 20 años\n",
      "  While:\n",
      "Luis tu edad esta entre 40 y 20 años\n",
      "Carla tu edad es menor de 20 años\n",
      "Felipe tu edad es menor de 20 años\n",
      "Monica tu edad esta entre 40 y 20 años\n",
      "No hay mas datos relevantes\n"
     ]
    }
   ],
   "source": [
    "#Retos bucles\n",
    "\n",
    "#Reto 2\n",
    "persona1 = {\"nombre\" : \"Luis\",\n",
    "\"apellido\" : \"Perez\",\n",
    "\"anyoNacimiento\" : 1980,\n",
    "\"aficiones\": [\"bailar\", \"escribir\"],\n",
    "\"dni\": { \"anyoExpedicion\" : 2004,\n",
    "\"lugarNacimento\": \"Tenerife\"},\n",
    "\"colorPelo\" : \"rubio\"}\n",
    "persona2 = {\"nombre\" : \"Carla\",\n",
    "\"apellido\" : \"Perez\",\n",
    "\"anyoNacimiento\" : 2009,\n",
    "\"aficiones\": [\"badminton\", \"caminar\"],\n",
    "\"dni\": { \"anyoExpedicion\" : 2002,\n",
    "\"lugarNacimento\": \"Segovia\"},\n",
    "\"colorPelo\" : \"negro\"}\n",
    "persona3 = {\"nombre\" : \"Felipe\",\n",
    "\"apellido\" : \"Perez\",\n",
    "\"anyoNacimiento\" : 2003,\n",
    "\"aficiones\": [\"baloncesto\", \"programacion\"],\n",
    "\"dni\": { \"anyoExpedicion\" : 2011,\n",
    "\"lugarNacimento\": \"Zamora\"},\n",
    "\"colorPelo\" : \"rubio\"}\n",
    "persona4 = {\"nombre\" :  \"Monica\",\n",
    "\"apellido\" : \"Perez\",\n",
    "\"anyoNacimiento\" : 1997,\n",
    "\"aficiones\": [\"baile\", \"pintar\"],\n",
    "\"dni\": { \"anyoExpedicion\" : 2011,\n",
    "\"lugarNacimento\": \"Pontevedra\"},\n",
    "\"colorPelo\" : \"castaño\"}\n",
    "personas = [persona1, persona2, persona3, persona4]\n",
    "try:\n",
    "    print(\"Elementos de la lista personas\")\n",
    "    print(\"  For:\")\n",
    "    for i in range(len(personas)):\n",
    "        print(personas[i])\n",
    "    print(\"  While:\")\n",
    "    i = 0\n",
    "    while(i<len(personas)):\n",
    "        print(personas[i])\n",
    "        i = i + 1\n",
    "    print(\"Nacidos entre 1978 y 2000\")\n",
    "    print(\"  For:\")\n",
    "    for persona in personas:\n",
    "        if 1978 < persona[\"anyoNacimiento\"] < 2000: print(persona[\"nombre\"], \"tu edad esta entre 40 y 20 años\")\n",
    "        else: print(persona[\"nombre\"], \"tu edad es menor de 20 años\")\n",
    "    print(\"  While:\")\n",
    "    b = 0\n",
    "    while b < len(personas):\n",
    "        persona = personas[b]\n",
    "        if 1978 < persona[\"anyoNacimiento\"] < 2000: print(persona[\"nombre\"], \"tu edad esta entre 40 y 20 años\")\n",
    "        else: print(persona[\"nombre\"], \"tu edad es menor de 20 años\")\n",
    "        b = b + 1\n",
    "    personas[0][\"aficiones\"]= [\"bailar\", \"escribir\", \"Jugar a la play\"]\n",
    "    personas[1][\"aficiones\"]= [\"badminton\", \"caminar\", \"Jugar a la play\"]\n",
    "    personas[2][\"aficiones\"]= [\"baloncesto\", \"programacion\", \"Jugar a la play\"]\n",
    "    personas[3][\"aficiones\"]= [\"baile\", \"pintar\", \"Jugar a la play\"]\n",
    "except:\n",
    "    print(\"Error al introducir la informacion\")\n",
    "finally:\n",
    "    print(\"No hay mas datos relevantes\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "90515d67-0121-4b23-9400-45e2a526cab1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "¿De qué número calculo el factorial?:  6\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "El factorial de  6  es  720\n",
      "Múltiplos de 2:\n",
      "2\n",
      "4\n",
      "6\n",
      "8\n",
      "10\n",
      "Suma de los 100 primeros números: 5050\n",
      "Índice de la primera ocurrencia del nombre Pepe: 3\n",
      "Suma de dos listas de 100 números aleatorios entre 0 y 20:\n",
      "[21, 22, 29, 13, 37]\n",
      "El programa ha finalizado\n"
     ]
    }
   ],
   "source": [
    "#Retos bucles\n",
    "\n",
    "#Reto 3\n",
    "try:\n",
    "    #Calcular el factorial de un numero dado, primero utilizando la sentencia for y luego con while.\n",
    "    n=int(input(\"¿De qué número calculo el factorial?: \"))\n",
    "    fact = list(range(n+1))\n",
    "    fact.pop(0)\n",
    "    f = 1\n",
    "    for i in range(1, n+1):\n",
    "        f = f * i\n",
    "    print(\"El factorial de \",n,\" es \",f)\n",
    "    #Dado una lista de números, buscar si existe algún numero de esa lista que sea múltiplo de 2 utilizando la sentencia while.\n",
    "    lista_num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n",
    "    print(\"Múltiplos de 2:\")\n",
    "    i = 1\n",
    "    while(i<10):\n",
    "        i = i + 1\n",
    "        if i % 2 == 0:  \n",
    "            print(lista_num[i-1])      \n",
    "    #Realizar la suma de los 100 primeros números. Utilizar el bucle que mejor se adapte al problema.\n",
    "    fact = list(range(101))\n",
    "    fact.pop(0)\n",
    "    f = 0\n",
    "    for i in range(1, 101):\n",
    "        f = f + i\n",
    "    print(\"Suma de los 100 primeros números: \"+str(f))\n",
    "    #Dado una lista de nombres mostrar el índice de la primera ocurrencia del nombre “Pepe”. Utilizar el bucle que mejor se adapte al problema.\n",
    "    nombres = [\"Carlos\", \"Jose\", \"Raquel\", \"Pepe\", \"Luana\", \"Federica\", \"Pepe\", \"Sergio\"]\n",
    "    p = 0\n",
    "    while nombres[p-1] != \"Pepe\":\n",
    "        if nombres[p] == \"Pepe\":\n",
    "            print(\"Índice de la primera ocurrencia del nombre Pepe: \"+ str(p))\n",
    "        p = p + 1\n",
    "    #Generar dos listas de 100 números aleatorios entre 0 y 20.\n",
    "    import random\n",
    "    lista1 = [random.randint(0, 20) for x in range(100)]\n",
    "    lista2 = [random.randint(0, 20) for x in range(100)]\n",
    "    #Realizar la suma de los dos listas anteriores.\n",
    "    lista3 = [random.randint(0,0) for x in range(5)]\n",
    "    for i in range(0,5):\n",
    "            lista3[i] = lista1[i] + lista2[i]\n",
    "    print(\"Suma de dos listas de 100 números aleatorios entre 0 y 20:\")\n",
    "    print(lista3)\n",
    "    #Utilizar los bloques try-except-else-finally para tratar las posibles excepciones que ocurran.\n",
    "except:\n",
    "    print(\"Error de dato\")\n",
    "finally:\n",
    "    print(\"El programa ha finalizado\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7a0983c-aad4-49da-b70b-c6950d35875d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
